repos:
- repo: local
  hooks:
  - id: ruff
    name: ruff
    entry: ruff check --force-exclude .
    language: python
    require_serial: true
    pass_filenames: false
    always_run: true
  - id: ruff-format
    name: ruff-format
    entry: ruff format --force-exclude .
    language: python
    require_serial: true
    pass_filenames: false
    always_run: true
