services:
- type: web
  name: frontend
  runtime: node
  plan: free
  buildCommand: cd frontend; npm install
  startCommand: cd frontend; npm run build; npm run start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_BACKEND_URL
    value: https://backend-87oq.onrender.com
- type: web
  name: backend
  env: python
  plan: free
  buildCommand: cd backend; poetry install
  startCommand: cd backend; poetry run fastapi run render_backend/main.py --port 10000
  autoDeploy: true
  envVars:
  - key: FRONTEND_URL
    value: https://frontend-vv2s.onrender.com
  - key: PYTHON_VERSION
    value: 3.12.7
  - key: PORT
    # Don't forget to update the startCommand if you change this.
    value: 10000
