services:
- type: web
  name: frontend
  runtime: node
  plan: free
  buildCommand: cd frontend; yarn; yarn build
  startCommand: cd frontend; yarn start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production
- type: web
  name: backend
  env: python
  plan: free
  buildCommand: cd backend; poetry install
  startCommand: cd backend; poetry run fastapi run render_backend/main.py
  autoDeploy: false
  envVars:
  - key: FRONTEND_URL
    value: http://localhost:3000
  - key: PYTHON_VERSION
    value: 3.12.7
# Uncomment the following to deploy this app as a static site on render
# - type: web
#   name: nextjs-static
#   runtime: static
#   buildCommand: yarn; yarn build
#   staticPublishPath: out
#   pullRequestPreviewsEnabled: true     # optional
#   envVars:
#   - key: NODE_ENV
#     value: production

