services:
- type: web
  name: frontend
  runtime: docker
  plan: free
  rootDir: frontend
  autoDeploy: true
  # This didn't work for me, so I switched it to load an ENV file instead.
  # envVars:
  # - key: NEXT_PUBLIC_BACKEND_URL
  #   value: https://backend-87oq.onrender.com
- type: web
  name: backend
  runtime: docker
  plan: free
  rootDir: backend
  autoDeploy: true
  envVars:
  - key: FRONTEND_URL
    value: https://frontend-vv2s.onrender.com
