services:
- type: web
  name: frontend
  runtime: docker
  plan: free
  dockerfilePath: frontend/dockerfile
  dockerContext: frontend/
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_BACKEND_URL
    value: https://backend-87oq.onrender.com
- type: web
  name: backend
  runtime: docker
  plan: free
  dockerfilePath: backend/dockerfile
  dockerContext: backend/
  autoDeploy: true
  envVars:
  - key: FRONTEND_URL
    value: https://frontend-vv2s.onrender.com
