// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lobby.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PositionSessionStateResponse contains the current lobby/session state for position based state management.
type PositionSessionStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerPositions map[int32]*PlayerInfo  `protobuf:"bytes,1,rep,name=player_positions,json=playerPositions,proto3" json:"player_positions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PositionSessionStateResponse) Reset() {
	*x = PositionSessionStateResponse{}
	mi := &file_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSessionStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSessionStateResponse) ProtoMessage() {}

func (x *PositionSessionStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSessionStateResponse.ProtoReflect.Descriptor instead.
func (*PositionSessionStateResponse) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *PositionSessionStateResponse) GetPlayerPositions() map[int32]*PlayerInfo {
	if x != nil {
		return x.PlayerPositions
	}
	return nil
}

// Client requests to set their player position
type SetPlayerPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerPositionRequest) Reset() {
	*x = SetPlayerPositionRequest{}
	mi := &file_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerPositionRequest) ProtoMessage() {}

func (x *SetPlayerPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerPositionRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerPositionRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *SetPlayerPositionRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Client requests to leave their current position
type RemovePlayerPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePlayerPositionRequest) Reset() {
	*x = RemovePlayerPositionRequest{}
	mi := &file_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePlayerPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePlayerPositionRequest) ProtoMessage() {}

func (x *RemovePlayerPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePlayerPositionRequest.ProtoReflect.Descriptor instead.
func (*RemovePlayerPositionRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *RemovePlayerPositionRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_lobby_proto protoreflect.FileDescriptor

const file_lobby_proto_rawDesc = "" +
	"\n" +
	"\vlobby.proto\x12\x0fgamessite.lobby\x1a\fcommon.proto\"\xef\x01\n" +
	"\x1cPositionSessionStateResponse\x12m\n" +
	"\x10player_positions\x18\x01 \x03(\v2B.gamessite.lobby.PositionSessionStateResponse.PlayerPositionsEntryR\x0fplayerPositions\x1a`\n" +
	"\x14PlayerPositionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.gamessite.common.PlayerInfoR\x05value:\x028\x01\"6\n" +
	"\x18SetPlayerPositionRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\"9\n" +
	"\x1bRemovePlayerPositionRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bpositionB\xb0\x01\n" +
	"\x13com.gamessite.lobbyB\n" +
	"LobbyProtoP\x01Z0github.com/AlexWendland/games-site/backend/proto\xa2\x02\x03GLX\xaa\x02\x0fGamessite.Lobby\xca\x02\x0fGamessite\\Lobby\xe2\x02\x1bGamessite\\Lobby\\GPBMetadata\xea\x02\x10Gamessite::Lobbyb\x06proto3"

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData []byte
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)))
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lobby_proto_goTypes = []any{
	(*PositionSessionStateResponse)(nil), // 0: gamessite.lobby.PositionSessionStateResponse
	(*SetPlayerPositionRequest)(nil),     // 1: gamessite.lobby.SetPlayerPositionRequest
	(*RemovePlayerPositionRequest)(nil),  // 2: gamessite.lobby.RemovePlayerPositionRequest
	nil,                                  // 3: gamessite.lobby.PositionSessionStateResponse.PlayerPositionsEntry
	(*PlayerInfo)(nil),                   // 4: gamessite.common.PlayerInfo
}
var file_lobby_proto_depIdxs = []int32{
	3, // 0: gamessite.lobby.PositionSessionStateResponse.player_positions:type_name -> gamessite.lobby.PositionSessionStateResponse.PlayerPositionsEntry
	4, // 1: gamessite.lobby.PositionSessionStateResponse.PlayerPositionsEntry.value:type_name -> gamessite.common.PlayerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
