// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Metadata:
	//
	//	*GameMetadataResponse_TicTacToeMetadata
	Metadata      isGameMetadataResponse_Metadata `protobuf_oneof:"metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMetadataResponse) Reset() {
	*x = GameMetadataResponse{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMetadataResponse) ProtoMessage() {}

func (x *GameMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMetadataResponse.ProtoReflect.Descriptor instead.
func (*GameMetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *GameMetadataResponse) GetMetadata() isGameMetadataResponse_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GameMetadataResponse) GetTicTacToeMetadata() *TicTacToeMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*GameMetadataResponse_TicTacToeMetadata); ok {
			return x.TicTacToeMetadata
		}
	}
	return nil
}

type isGameMetadataResponse_Metadata interface {
	isGameMetadataResponse_Metadata()
}

type GameMetadataResponse_TicTacToeMetadata struct {
	TicTacToeMetadata *TicTacToeMetadata `protobuf:"bytes,1,opt,name=tic_tac_toe_metadata,json=ticTacToeMetadata,proto3,oneof"`
}

func (*GameMetadataResponse_TicTacToeMetadata) isGameMetadataResponse_Metadata() {}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\x12gamessite.metadata\x1a\x0ftictactoe.proto\"}\n" +
	"\x14GameMetadataResponse\x12Y\n" +
	"\x14tic_tac_toe_metadata\x18\x01 \x01(\v2&.gamessite.tictactoe.TicTacToeMetadataH\x00R\x11ticTacToeMetadataB\n" +
	"\n" +
	"\bmetadataB\xc2\x01\n" +
	"\x16com.gamessite.metadataB\rMetadataProtoP\x01Z0github.com/AlexWendland/games-site/backend/proto\xa2\x02\x03GMX\xaa\x02\x12Gamessite.Metadata\xca\x02\x12Gamessite\\Metadata\xe2\x02\x1eGamessite\\Metadata\\GPBMetadata\xea\x02\x13Gamessite::Metadatab\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metadata_proto_goTypes = []any{
	(*GameMetadataResponse)(nil), // 0: gamessite.metadata.GameMetadataResponse
	(*TicTacToeMetadata)(nil),    // 1: gamessite.tictactoe.TicTacToeMetadata
}
var file_metadata_proto_depIdxs = []int32{
	1, // 0: gamessite.metadata.GameMetadataResponse.tic_tac_toe_metadata:type_name -> gamessite.tictactoe.TicTacToeMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	file_tictactoe_proto_init()
	file_metadata_proto_msgTypes[0].OneofWrappers = []any{
		(*GameMetadataResponse_TicTacToeMetadata)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
