// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tictactoe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicTacToeModel int32

const (
	TicTacToeModel_TIC_TAC_TOE_MODEL_UNSPECIFIED TicTacToeModel = 0
	TicTacToeModel_TIC_TAC_TOE_MODEL_EASY        TicTacToeModel = 1
	TicTacToeModel_TIC_TAC_TOE_MODEL_MEDIUM      TicTacToeModel = 2
	TicTacToeModel_TIC_TAC_TOE_MODEL_HARD        TicTacToeModel = 3
)

// Enum value maps for TicTacToeModel.
var (
	TicTacToeModel_name = map[int32]string{
		0: "TIC_TAC_TOE_MODEL_UNSPECIFIED",
		1: "TIC_TAC_TOE_MODEL_EASY",
		2: "TIC_TAC_TOE_MODEL_MEDIUM",
		3: "TIC_TAC_TOE_MODEL_HARD",
	}
	TicTacToeModel_value = map[string]int32{
		"TIC_TAC_TOE_MODEL_UNSPECIFIED": 0,
		"TIC_TAC_TOE_MODEL_EASY":        1,
		"TIC_TAC_TOE_MODEL_MEDIUM":      2,
		"TIC_TAC_TOE_MODEL_HARD":        3,
	}
)

func (x TicTacToeModel) Enum() *TicTacToeModel {
	p := new(TicTacToeModel)
	*p = x
	return p
}

func (x TicTacToeModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicTacToeModel) Descriptor() protoreflect.EnumDescriptor {
	return file_tictactoe_proto_enumTypes[0].Descriptor()
}

func (TicTacToeModel) Type() protoreflect.EnumType {
	return &file_tictactoe_proto_enumTypes[0]
}

func (x TicTacToeModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicTacToeModel.Descriptor instead.
func (TicTacToeModel) EnumDescriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{0}
}

// TicTacToe game state sent from server to client
type TicTacToeGameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         []int32                `protobuf:"varint,1,rep,packed,name=board,proto3" json:"board,omitempty"`                                // 9 elements: move numbers (-1 = empty, 0+ = move number)
	Winner        *int32                 `protobuf:"varint,2,opt,name=winner,proto3,oneof" json:"winner,omitempty"`                               // Player number who won (0 or 1), null if no winner
	WinningLine   []int32                `protobuf:"varint,3,rep,packed,name=winning_line,json=winningLine,proto3" json:"winning_line,omitempty"` // Board positions that form the winning line (empty if no winner)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicTacToeGameState) Reset() {
	*x = TicTacToeGameState{}
	mi := &file_tictactoe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicTacToeGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicTacToeGameState) ProtoMessage() {}

func (x *TicTacToeGameState) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicTacToeGameState.ProtoReflect.Descriptor instead.
func (*TicTacToeGameState) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{0}
}

func (x *TicTacToeGameState) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *TicTacToeGameState) GetWinner() int32 {
	if x != nil && x.Winner != nil {
		return *x.Winner
	}
	return 0
}

func (x *TicTacToeGameState) GetWinningLine() []int32 {
	if x != nil {
		return x.WinningLine
	}
	return nil
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"` // Board position 0-8
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	mi := &file_tictactoe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{1}
}

func (x *MakeMoveRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Client requests to add an AI player in a particular position
type TicTacToeAddAIPlayerInPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`                                   // Player position (0 or 1)
	Model         TicTacToeModel         `protobuf:"varint,2,opt,name=model,proto3,enum=gamessite.tictactoe.TicTacToeModel" json:"model,omitempty"` // AI model type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicTacToeAddAIPlayerInPositionRequest) Reset() {
	*x = TicTacToeAddAIPlayerInPositionRequest{}
	mi := &file_tictactoe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicTacToeAddAIPlayerInPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicTacToeAddAIPlayerInPositionRequest) ProtoMessage() {}

func (x *TicTacToeAddAIPlayerInPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicTacToeAddAIPlayerInPositionRequest.ProtoReflect.Descriptor instead.
func (*TicTacToeAddAIPlayerInPositionRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{2}
}

func (x *TicTacToeAddAIPlayerInPositionRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *TicTacToeAddAIPlayerInPositionRequest) GetModel() TicTacToeModel {
	if x != nil {
		return x.Model
	}
	return TicTacToeModel_TIC_TAC_TOE_MODEL_UNSPECIFIED
}

type ClientTicTacToeWebsocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientTicTacToeWebsocketMessage_MakeMove
	//	*ClientTicTacToeWebsocketMessage_SetPlayerPosition
	//	*ClientTicTacToeWebsocketMessage_RemovePlayerPosition
	//	*ClientTicTacToeWebsocketMessage_AddAiPlayer
	Message       isClientTicTacToeWebsocketMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTicTacToeWebsocketMessage) Reset() {
	*x = ClientTicTacToeWebsocketMessage{}
	mi := &file_tictactoe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTicTacToeWebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTicTacToeWebsocketMessage) ProtoMessage() {}

func (x *ClientTicTacToeWebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTicTacToeWebsocketMessage.ProtoReflect.Descriptor instead.
func (*ClientTicTacToeWebsocketMessage) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTicTacToeWebsocketMessage) GetMessage() isClientTicTacToeWebsocketMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientTicTacToeWebsocketMessage) GetMakeMove() *MakeMoveRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientTicTacToeWebsocketMessage_MakeMove); ok {
			return x.MakeMove
		}
	}
	return nil
}

func (x *ClientTicTacToeWebsocketMessage) GetSetPlayerPosition() *SetPlayerPositionRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientTicTacToeWebsocketMessage_SetPlayerPosition); ok {
			return x.SetPlayerPosition
		}
	}
	return nil
}

func (x *ClientTicTacToeWebsocketMessage) GetRemovePlayerPosition() *RemovePlayerPositionRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientTicTacToeWebsocketMessage_RemovePlayerPosition); ok {
			return x.RemovePlayerPosition
		}
	}
	return nil
}

func (x *ClientTicTacToeWebsocketMessage) GetAddAiPlayer() *TicTacToeAddAIPlayerInPositionRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientTicTacToeWebsocketMessage_AddAiPlayer); ok {
			return x.AddAiPlayer
		}
	}
	return nil
}

type isClientTicTacToeWebsocketMessage_Message interface {
	isClientTicTacToeWebsocketMessage_Message()
}

type ClientTicTacToeWebsocketMessage_MakeMove struct {
	MakeMove *MakeMoveRequest `protobuf:"bytes,1,opt,name=make_move,json=makeMove,proto3,oneof"`
}

type ClientTicTacToeWebsocketMessage_SetPlayerPosition struct {
	SetPlayerPosition *SetPlayerPositionRequest `protobuf:"bytes,2,opt,name=set_player_position,json=setPlayerPosition,proto3,oneof"`
}

type ClientTicTacToeWebsocketMessage_RemovePlayerPosition struct {
	RemovePlayerPosition *RemovePlayerPositionRequest `protobuf:"bytes,3,opt,name=remove_player_position,json=removePlayerPosition,proto3,oneof"`
}

type ClientTicTacToeWebsocketMessage_AddAiPlayer struct {
	AddAiPlayer *TicTacToeAddAIPlayerInPositionRequest `protobuf:"bytes,4,opt,name=add_ai_player,json=addAiPlayer,proto3,oneof"`
}

func (*ClientTicTacToeWebsocketMessage_MakeMove) isClientTicTacToeWebsocketMessage_Message() {}

func (*ClientTicTacToeWebsocketMessage_SetPlayerPosition) isClientTicTacToeWebsocketMessage_Message() {
}

func (*ClientTicTacToeWebsocketMessage_RemovePlayerPosition) isClientTicTacToeWebsocketMessage_Message() {
}

func (*ClientTicTacToeWebsocketMessage_AddAiPlayer) isClientTicTacToeWebsocketMessage_Message() {}

type ServerTicTacToeWebsocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerTicTacToeWebsocketMessage_GameState
	//	*ServerTicTacToeWebsocketMessage_SessionState
	//	*ServerTicTacToeWebsocketMessage_Error
	//	*ServerTicTacToeWebsocketMessage_SimpleResponse
	Message       isServerTicTacToeWebsocketMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTicTacToeWebsocketMessage) Reset() {
	*x = ServerTicTacToeWebsocketMessage{}
	mi := &file_tictactoe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTicTacToeWebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTicTacToeWebsocketMessage) ProtoMessage() {}

func (x *ServerTicTacToeWebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTicTacToeWebsocketMessage.ProtoReflect.Descriptor instead.
func (*ServerTicTacToeWebsocketMessage) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{4}
}

func (x *ServerTicTacToeWebsocketMessage) GetMessage() isServerTicTacToeWebsocketMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerTicTacToeWebsocketMessage) GetGameState() *TicTacToeGameState {
	if x != nil {
		if x, ok := x.Message.(*ServerTicTacToeWebsocketMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *ServerTicTacToeWebsocketMessage) GetSessionState() *PositionSessionStateResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerTicTacToeWebsocketMessage_SessionState); ok {
			return x.SessionState
		}
	}
	return nil
}

func (x *ServerTicTacToeWebsocketMessage) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerTicTacToeWebsocketMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerTicTacToeWebsocketMessage) GetSimpleResponse() *SimpleResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerTicTacToeWebsocketMessage_SimpleResponse); ok {
			return x.SimpleResponse
		}
	}
	return nil
}

type isServerTicTacToeWebsocketMessage_Message interface {
	isServerTicTacToeWebsocketMessage_Message()
}

type ServerTicTacToeWebsocketMessage_GameState struct {
	GameState *TicTacToeGameState `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3,oneof"`
}

type ServerTicTacToeWebsocketMessage_SessionState struct {
	SessionState *PositionSessionStateResponse `protobuf:"bytes,2,opt,name=session_state,json=sessionState,proto3,oneof"`
}

type ServerTicTacToeWebsocketMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerTicTacToeWebsocketMessage_SimpleResponse struct {
	SimpleResponse *SimpleResponse `protobuf:"bytes,4,opt,name=simple_response,json=simpleResponse,proto3,oneof"`
}

func (*ServerTicTacToeWebsocketMessage_GameState) isServerTicTacToeWebsocketMessage_Message() {}

func (*ServerTicTacToeWebsocketMessage_SessionState) isServerTicTacToeWebsocketMessage_Message() {}

func (*ServerTicTacToeWebsocketMessage_Error) isServerTicTacToeWebsocketMessage_Message() {}

func (*ServerTicTacToeWebsocketMessage_SimpleResponse) isServerTicTacToeWebsocketMessage_Message() {}

type TicTacToeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicTacToeMetadata) Reset() {
	*x = TicTacToeMetadata{}
	mi := &file_tictactoe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicTacToeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicTacToeMetadata) ProtoMessage() {}

func (x *TicTacToeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicTacToeMetadata.ProtoReflect.Descriptor instead.
func (*TicTacToeMetadata) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{5}
}

// REST API Messages
type CreateTicTacToeGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicTacToeGameRequest) Reset() {
	*x = CreateTicTacToeGameRequest{}
	mi := &file_tictactoe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicTacToeGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicTacToeGameRequest) ProtoMessage() {}

func (x *CreateTicTacToeGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicTacToeGameRequest.ProtoReflect.Descriptor instead.
func (*CreateTicTacToeGameRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{6}
}

type CreateTicTacToeGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // The generated game ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicTacToeGameResponse) Reset() {
	*x = CreateTicTacToeGameResponse{}
	mi := &file_tictactoe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicTacToeGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicTacToeGameResponse) ProtoMessage() {}

func (x *CreateTicTacToeGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicTacToeGameResponse.ProtoReflect.Descriptor instead.
func (*CreateTicTacToeGameResponse) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTicTacToeGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

var File_tictactoe_proto protoreflect.FileDescriptor

const file_tictactoe_proto_rawDesc = "" +
	"\n" +
	"\x0ftictactoe.proto\x12\x13gamessite.tictactoe\x1a\fcommon.proto\x1a\vlobby.proto\"u\n" +
	"\x12TicTacToeGameState\x12\x14\n" +
	"\x05board\x18\x01 \x03(\x05R\x05board\x12\x1b\n" +
	"\x06winner\x18\x02 \x01(\x05H\x00R\x06winner\x88\x01\x01\x12!\n" +
	"\fwinning_line\x18\x03 \x03(\x05R\vwinningLineB\t\n" +
	"\a_winner\"-\n" +
	"\x0fMakeMoveRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\"~\n" +
	"%TicTacToeAddAIPlayerInPositionRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x129\n" +
	"\x05model\x18\x02 \x01(\x0e2#.gamessite.tictactoe.TicTacToeModelR\x05model\"\x96\x03\n" +
	"\x1fClientTicTacToeWebsocketMessage\x12C\n" +
	"\tmake_move\x18\x01 \x01(\v2$.gamessite.tictactoe.MakeMoveRequestH\x00R\bmakeMove\x12[\n" +
	"\x13set_player_position\x18\x02 \x01(\v2).gamessite.lobby.SetPlayerPositionRequestH\x00R\x11setPlayerPosition\x12d\n" +
	"\x16remove_player_position\x18\x03 \x01(\v2,.gamessite.lobby.RemovePlayerPositionRequestH\x00R\x14removePlayerPosition\x12`\n" +
	"\radd_ai_player\x18\x04 \x01(\v2:.gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequestH\x00R\vaddAiPlayerB\t\n" +
	"\amessage\"\xd2\x02\n" +
	"\x1fServerTicTacToeWebsocketMessage\x12H\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2'.gamessite.tictactoe.TicTacToeGameStateH\x00R\tgameState\x12T\n" +
	"\rsession_state\x18\x02 \x01(\v2-.gamessite.lobby.PositionSessionStateResponseH\x00R\fsessionState\x127\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.gamessite.common.ErrorResponseH\x00R\x05error\x12K\n" +
	"\x0fsimple_response\x18\x04 \x01(\v2 .gamessite.common.SimpleResponseH\x00R\x0esimpleResponseB\t\n" +
	"\amessage\"\x13\n" +
	"\x11TicTacToeMetadata\"\x1c\n" +
	"\x1aCreateTicTacToeGameRequest\"6\n" +
	"\x1bCreateTicTacToeGameResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId*\x89\x01\n" +
	"\x0eTicTacToeModel\x12!\n" +
	"\x1dTIC_TAC_TOE_MODEL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TIC_TAC_TOE_MODEL_EASY\x10\x01\x12\x1c\n" +
	"\x18TIC_TAC_TOE_MODEL_MEDIUM\x10\x02\x12\x1a\n" +
	"\x16TIC_TAC_TOE_MODEL_HARD\x10\x03B\xc8\x01\n" +
	"\x17com.gamessite.tictactoeB\x0eTictactoeProtoP\x01Z0github.com/AlexWendland/games-site/backend/proto\xa2\x02\x03GTX\xaa\x02\x13Gamessite.Tictactoe\xca\x02\x13Gamessite\\Tictactoe\xe2\x02\x1fGamessite\\Tictactoe\\GPBMetadata\xea\x02\x14Gamessite::Tictactoeb\x06proto3"

var (
	file_tictactoe_proto_rawDescOnce sync.Once
	file_tictactoe_proto_rawDescData []byte
)

func file_tictactoe_proto_rawDescGZIP() []byte {
	file_tictactoe_proto_rawDescOnce.Do(func() {
		file_tictactoe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tictactoe_proto_rawDesc), len(file_tictactoe_proto_rawDesc)))
	})
	return file_tictactoe_proto_rawDescData
}

var file_tictactoe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tictactoe_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tictactoe_proto_goTypes = []any{
	(TicTacToeModel)(0),                           // 0: gamessite.tictactoe.TicTacToeModel
	(*TicTacToeGameState)(nil),                    // 1: gamessite.tictactoe.TicTacToeGameState
	(*MakeMoveRequest)(nil),                       // 2: gamessite.tictactoe.MakeMoveRequest
	(*TicTacToeAddAIPlayerInPositionRequest)(nil), // 3: gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequest
	(*ClientTicTacToeWebsocketMessage)(nil),       // 4: gamessite.tictactoe.ClientTicTacToeWebsocketMessage
	(*ServerTicTacToeWebsocketMessage)(nil),       // 5: gamessite.tictactoe.ServerTicTacToeWebsocketMessage
	(*TicTacToeMetadata)(nil),                     // 6: gamessite.tictactoe.TicTacToeMetadata
	(*CreateTicTacToeGameRequest)(nil),            // 7: gamessite.tictactoe.CreateTicTacToeGameRequest
	(*CreateTicTacToeGameResponse)(nil),           // 8: gamessite.tictactoe.CreateTicTacToeGameResponse
	(*SetPlayerPositionRequest)(nil),              // 9: gamessite.lobby.SetPlayerPositionRequest
	(*RemovePlayerPositionRequest)(nil),           // 10: gamessite.lobby.RemovePlayerPositionRequest
	(*PositionSessionStateResponse)(nil),          // 11: gamessite.lobby.PositionSessionStateResponse
	(*ErrorResponse)(nil),                         // 12: gamessite.common.ErrorResponse
	(*SimpleResponse)(nil),                        // 13: gamessite.common.SimpleResponse
}
var file_tictactoe_proto_depIdxs = []int32{
	0,  // 0: gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequest.model:type_name -> gamessite.tictactoe.TicTacToeModel
	2,  // 1: gamessite.tictactoe.ClientTicTacToeWebsocketMessage.make_move:type_name -> gamessite.tictactoe.MakeMoveRequest
	9,  // 2: gamessite.tictactoe.ClientTicTacToeWebsocketMessage.set_player_position:type_name -> gamessite.lobby.SetPlayerPositionRequest
	10, // 3: gamessite.tictactoe.ClientTicTacToeWebsocketMessage.remove_player_position:type_name -> gamessite.lobby.RemovePlayerPositionRequest
	3,  // 4: gamessite.tictactoe.ClientTicTacToeWebsocketMessage.add_ai_player:type_name -> gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequest
	1,  // 5: gamessite.tictactoe.ServerTicTacToeWebsocketMessage.game_state:type_name -> gamessite.tictactoe.TicTacToeGameState
	11, // 6: gamessite.tictactoe.ServerTicTacToeWebsocketMessage.session_state:type_name -> gamessite.lobby.PositionSessionStateResponse
	12, // 7: gamessite.tictactoe.ServerTicTacToeWebsocketMessage.error:type_name -> gamessite.common.ErrorResponse
	13, // 8: gamessite.tictactoe.ServerTicTacToeWebsocketMessage.simple_response:type_name -> gamessite.common.SimpleResponse
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_tictactoe_proto_init() }
func file_tictactoe_proto_init() {
	if File_tictactoe_proto != nil {
		return
	}
	file_common_proto_init()
	file_lobby_proto_init()
	file_tictactoe_proto_msgTypes[0].OneofWrappers = []any{}
	file_tictactoe_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientTicTacToeWebsocketMessage_MakeMove)(nil),
		(*ClientTicTacToeWebsocketMessage_SetPlayerPosition)(nil),
		(*ClientTicTacToeWebsocketMessage_RemovePlayerPosition)(nil),
		(*ClientTicTacToeWebsocketMessage_AddAiPlayer)(nil),
	}
	file_tictactoe_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerTicTacToeWebsocketMessage_GameState)(nil),
		(*ServerTicTacToeWebsocketMessage_SessionState)(nil),
		(*ServerTicTacToeWebsocketMessage_Error)(nil),
		(*ServerTicTacToeWebsocketMessage_SimpleResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tictactoe_proto_rawDesc), len(file_tictactoe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tictactoe_proto_goTypes,
		DependencyIndexes: file_tictactoe_proto_depIdxs,
		EnumInfos:         file_tictactoe_proto_enumTypes,
		MessageInfos:      file_tictactoe_proto_msgTypes,
	}.Build()
	File_tictactoe_proto = out.File
	file_tictactoe_proto_goTypes = nil
	file_tictactoe_proto_depIdxs = nil
}
