// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file auth.proto (package gamessite.auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth.proto.
 */
export const file_auth: GenFile = /*@__PURE__*/
  fileDesc("CgphdXRoLnByb3RvEg5nYW1lc3NpdGUuYXV0aCI1Cg9SZWdpc3RlclJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiMgoMTG9naW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIi4KDEF1dGhSZXNwb25zZRINCgV0b2tlbhgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIiMKD1dTVG9rZW5SZXNwb25zZRIQCgh3c190b2tlbhgBIAEoCSI1ChBVc2VySW5mb1Jlc3BvbnNlEg8KB3VzZXJfaWQYASABKAkSEAoIdXNlcm5hbWUYAiABKAlCqgEKEmNvbS5nYW1lc3NpdGUuYXV0aEIJQXV0aFByb3RvUAFaMGdpdGh1Yi5jb20vQWxleFdlbmRsYW5kL2dhbWVzLXNpdGUvYmFja2VuZC9wcm90b6ICA0dBWKoCDkdhbWVzc2l0ZS5BdXRoygIOR2FtZXNzaXRlXEF1dGjiAhpHYW1lc3NpdGVcQXV0aFxHUEJNZXRhZGF0YeoCD0dhbWVzc2l0ZTo6QXV0aGIGcHJvdG8z");

/**
 * @generated from message gamessite.auth.RegisterRequest
 */
export type RegisterRequest = Message<"gamessite.auth.RegisterRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message gamessite.auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_auth, 0);

/**
 * @generated from message gamessite.auth.LoginRequest
 */
export type LoginRequest = Message<"gamessite.auth.LoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message gamessite.auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth, 1);

/**
 * @generated from message gamessite.auth.AuthResponse
 */
export type AuthResponse = Message<"gamessite.auth.AuthResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message gamessite.auth.AuthResponse.
 * Use `create(AuthResponseSchema)` to create a new message.
 */
export const AuthResponseSchema: GenMessage<AuthResponse> = /*@__PURE__*/
  messageDesc(file_auth, 2);

/**
 * @generated from message gamessite.auth.WSTokenResponse
 */
export type WSTokenResponse = Message<"gamessite.auth.WSTokenResponse"> & {
  /**
   * @generated from field: string ws_token = 1;
   */
  wsToken: string;
};

/**
 * Describes the message gamessite.auth.WSTokenResponse.
 * Use `create(WSTokenResponseSchema)` to create a new message.
 */
export const WSTokenResponseSchema: GenMessage<WSTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth, 3);

/**
 * @generated from message gamessite.auth.UserInfoResponse
 */
export type UserInfoResponse = Message<"gamessite.auth.UserInfoResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;
};

/**
 * Describes the message gamessite.auth.UserInfoResponse.
 * Use `create(UserInfoResponseSchema)` to create a new message.
 */
export const UserInfoResponseSchema: GenMessage<UserInfoResponse> = /*@__PURE__*/
  messageDesc(file_auth, 4);

