// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file common.proto (package gamessite.common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SEGdhbWVzc2l0ZS5jb21tb24iQgoKUGxheWVySW5mbxIPCgd1c2VyX2lkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRINCgVpc19haRgDIAEoCCImCg1FcnJvclJlc3BvbnNlEhUKDWVycm9yX21lc3NhZ2UYASABKAkiIQoOU2ltcGxlUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCUK2AQoUY29tLmdhbWVzc2l0ZS5jb21tb25CC0NvbW1vblByb3RvUAFaMGdpdGh1Yi5jb20vQWxleFdlbmRsYW5kL2dhbWVzLXNpdGUvYmFja2VuZC9wcm90b6ICA0dDWKoCEEdhbWVzc2l0ZS5Db21tb27KAhBHYW1lc3NpdGVcQ29tbW9u4gIcR2FtZXNzaXRlXENvbW1vblxHUEJNZXRhZGF0YeoCEUdhbWVzc2l0ZTo6Q29tbW9uYgZwcm90bzM");

/**
 * PlayerInfo contains information about a player in a session
 *
 * @generated from message gamessite.common.PlayerInfo
 */
export type PlayerInfo = Message<"gamessite.common.PlayerInfo"> & {
  /**
   * For AI this is the AI type
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Display name for the player
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Whether this is an AI player
   *
   * @generated from field: bool is_ai = 3;
   */
  isAi: boolean;
};

/**
 * Describes the message gamessite.common.PlayerInfo.
 * Use `create(PlayerInfoSchema)` to create a new message.
 */
export const PlayerInfoSchema: GenMessage<PlayerInfo> = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * ErrorResponse is sent when an error occurs
 *
 * @generated from message gamessite.common.ErrorResponse
 */
export type ErrorResponse = Message<"gamessite.common.ErrorResponse"> & {
  /**
   * @generated from field: string error_message = 1;
   */
  errorMessage: string;
};

/**
 * Describes the message gamessite.common.ErrorResponse.
 * Use `create(ErrorResponseSchema)` to create a new message.
 */
export const ErrorResponseSchema: GenMessage<ErrorResponse> = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * SimpleResponse is sent for simple text messages
 *
 * @generated from message gamessite.common.SimpleResponse
 */
export type SimpleResponse = Message<"gamessite.common.SimpleResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message gamessite.common.SimpleResponse.
 * Use `create(SimpleResponseSchema)` to create a new message.
 */
export const SimpleResponseSchema: GenMessage<SimpleResponse> = /*@__PURE__*/
  messageDesc(file_common, 2);

