// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file lobby.proto (package gamessite.lobby, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerInfo } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file lobby.proto.
 */
export const file_lobby: GenFile = /*@__PURE__*/
  fileDesc("Cgtsb2JieS5wcm90bxIPZ2FtZXNzaXRlLmxvYmJ5ItIBChxQb3NpdGlvblNlc3Npb25TdGF0ZVJlc3BvbnNlElwKEHBsYXllcl9wb3NpdGlvbnMYASADKAsyQi5nYW1lc3NpdGUubG9iYnkuUG9zaXRpb25TZXNzaW9uU3RhdGVSZXNwb25zZS5QbGF5ZXJQb3NpdGlvbnNFbnRyeRpUChRQbGF5ZXJQb3NpdGlvbnNFbnRyeRILCgNrZXkYASABKAUSKwoFdmFsdWUYAiABKAsyHC5nYW1lc3NpdGUuY29tbW9uLlBsYXllckluZm86AjgBIiwKGFNldFBsYXllclBvc2l0aW9uUmVxdWVzdBIQCghwb3NpdGlvbhgBIAEoBSIvChtSZW1vdmVQbGF5ZXJQb3NpdGlvblJlcXVlc3QSEAoIcG9zaXRpb24YASABKAVCsAEKE2NvbS5nYW1lc3NpdGUubG9iYnlCCkxvYmJ5UHJvdG9QAVowZ2l0aHViLmNvbS9BbGV4V2VuZGxhbmQvZ2FtZXMtc2l0ZS9iYWNrZW5kL3Byb3RvogIDR0xYqgIPR2FtZXNzaXRlLkxvYmJ5ygIPR2FtZXNzaXRlXExvYmJ54gIbR2FtZXNzaXRlXExvYmJ5XEdQQk1ldGFkYXRh6gIQR2FtZXNzaXRlOjpMb2JieWIGcHJvdG8z", [file_common]);

/**
 * PositionSessionStateResponse contains the current lobby/session state for position based state management.
 *
 * @generated from message gamessite.lobby.PositionSessionStateResponse
 */
export type PositionSessionStateResponse = Message<"gamessite.lobby.PositionSessionStateResponse"> & {
  /**
   * @generated from field: map<int32, gamessite.common.PlayerInfo> player_positions = 1;
   */
  playerPositions: { [key: number]: PlayerInfo };
};

/**
 * Describes the message gamessite.lobby.PositionSessionStateResponse.
 * Use `create(PositionSessionStateResponseSchema)` to create a new message.
 */
export const PositionSessionStateResponseSchema: GenMessage<PositionSessionStateResponse> = /*@__PURE__*/
  messageDesc(file_lobby, 0);

/**
 * Client requests to set their player position
 *
 * @generated from message gamessite.lobby.SetPlayerPositionRequest
 */
export type SetPlayerPositionRequest = Message<"gamessite.lobby.SetPlayerPositionRequest"> & {
  /**
   * @generated from field: int32 position = 1;
   */
  position: number;
};

/**
 * Describes the message gamessite.lobby.SetPlayerPositionRequest.
 * Use `create(SetPlayerPositionRequestSchema)` to create a new message.
 */
export const SetPlayerPositionRequestSchema: GenMessage<SetPlayerPositionRequest> = /*@__PURE__*/
  messageDesc(file_lobby, 1);

/**
 * Client requests to leave their current position
 *
 * @generated from message gamessite.lobby.RemovePlayerPositionRequest
 */
export type RemovePlayerPositionRequest = Message<"gamessite.lobby.RemovePlayerPositionRequest"> & {
  /**
   * @generated from field: int32 position = 1;
   */
  position: number;
};

/**
 * Describes the message gamessite.lobby.RemovePlayerPositionRequest.
 * Use `create(RemovePlayerPositionRequestSchema)` to create a new message.
 */
export const RemovePlayerPositionRequestSchema: GenMessage<RemovePlayerPositionRequest> = /*@__PURE__*/
  messageDesc(file_lobby, 2);

