// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file metadata.proto (package gamessite.metadata, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TicTacToeMetadata } from "./tictactoe_pb";
import { file_tictactoe } from "./tictactoe_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file metadata.proto.
 */
export const file_metadata: GenFile = /*@__PURE__*/
  fileDesc("Cg5tZXRhZGF0YS5wcm90bxISZ2FtZXNzaXRlLm1ldGFkYXRhImoKFEdhbWVNZXRhZGF0YVJlc3BvbnNlEkYKFHRpY190YWNfdG9lX21ldGFkYXRhGAEgASgLMiYuZ2FtZXNzaXRlLnRpY3RhY3RvZS5UaWNUYWNUb2VNZXRhZGF0YUgAQgoKCG1ldGFkYXRhQsIBChZjb20uZ2FtZXNzaXRlLm1ldGFkYXRhQg1NZXRhZGF0YVByb3RvUAFaMGdpdGh1Yi5jb20vQWxleFdlbmRsYW5kL2dhbWVzLXNpdGUvYmFja2VuZC9wcm90b6ICA0dNWKoCEkdhbWVzc2l0ZS5NZXRhZGF0YcoCEkdhbWVzc2l0ZVxNZXRhZGF0YeICHkdhbWVzc2l0ZVxNZXRhZGF0YVxHUEJNZXRhZGF0YeoCE0dhbWVzc2l0ZTo6TWV0YWRhdGFiBnByb3RvMw", [file_tictactoe]);

/**
 * @generated from message gamessite.metadata.GameMetadataResponse
 */
export type GameMetadataResponse = Message<"gamessite.metadata.GameMetadataResponse"> & {
  /**
   * @generated from oneof gamessite.metadata.GameMetadataResponse.metadata
   */
  metadata: {
    /**
     * @generated from field: gamessite.tictactoe.TicTacToeMetadata tic_tac_toe_metadata = 1;
     */
    value: TicTacToeMetadata;
    case: "ticTacToeMetadata";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gamessite.metadata.GameMetadataResponse.
 * Use `create(GameMetadataResponseSchema)` to create a new message.
 */
export const GameMetadataResponseSchema: GenMessage<GameMetadataResponse> = /*@__PURE__*/
  messageDesc(file_metadata, 0);

