// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file tictactoe.proto (package gamessite.tictactoe, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ErrorResponse, SimpleResponse } from "./common_pb";
import { file_common } from "./common_pb";
import type { PositionSessionStateResponse, RemovePlayerPositionRequest, SetPlayerPositionRequest } from "./lobby_pb";
import { file_lobby } from "./lobby_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tictactoe.proto.
 */
export const file_tictactoe: GenFile = /*@__PURE__*/
  fileDesc("Cg90aWN0YWN0b2UucHJvdG8SE2dhbWVzc2l0ZS50aWN0YWN0b2UiWQoSVGljVGFjVG9lR2FtZVN0YXRlEg0KBWJvYXJkGAEgAygFEhMKBndpbm5lchgCIAEoBUgAiAEBEhQKDHdpbm5pbmdfbGluZRgDIAMoBUIJCgdfd2lubmVyIiMKD01ha2VNb3ZlUmVxdWVzdBIQCghwb3NpdGlvbhgBIAEoBSJtCiVUaWNUYWNUb2VBZGRBSVBsYXllckluUG9zaXRpb25SZXF1ZXN0EhAKCHBvc2l0aW9uGAEgASgFEjIKBW1vZGVsGAIgASgOMiMuZ2FtZXNzaXRlLnRpY3RhY3RvZS5UaWNUYWNUb2VNb2RlbCLWAgofQ2xpZW50VGljVGFjVG9lV2Vic29ja2V0TWVzc2FnZRI5CgltYWtlX21vdmUYASABKAsyJC5nYW1lc3NpdGUudGljdGFjdG9lLk1ha2VNb3ZlUmVxdWVzdEgAEkgKE3NldF9wbGF5ZXJfcG9zaXRpb24YAiABKAsyKS5nYW1lc3NpdGUubG9iYnkuU2V0UGxheWVyUG9zaXRpb25SZXF1ZXN0SAASTgoWcmVtb3ZlX3BsYXllcl9wb3NpdGlvbhgDIAEoCzIsLmdhbWVzc2l0ZS5sb2JieS5SZW1vdmVQbGF5ZXJQb3NpdGlvblJlcXVlc3RIABJTCg1hZGRfYWlfcGxheWVyGAQgASgLMjouZ2FtZXNzaXRlLnRpY3RhY3RvZS5UaWNUYWNUb2VBZGRBSVBsYXllckluUG9zaXRpb25SZXF1ZXN0SABCCQoHbWVzc2FnZSKiAgofU2VydmVyVGljVGFjVG9lV2Vic29ja2V0TWVzc2FnZRI9CgpnYW1lX3N0YXRlGAEgASgLMicuZ2FtZXNzaXRlLnRpY3RhY3RvZS5UaWNUYWNUb2VHYW1lU3RhdGVIABJGCg1zZXNzaW9uX3N0YXRlGAIgASgLMi0uZ2FtZXNzaXRlLmxvYmJ5LlBvc2l0aW9uU2Vzc2lvblN0YXRlUmVzcG9uc2VIABIwCgVlcnJvchgDIAEoCzIfLmdhbWVzc2l0ZS5jb21tb24uRXJyb3JSZXNwb25zZUgAEjsKD3NpbXBsZV9yZXNwb25zZRgEIAEoCzIgLmdhbWVzc2l0ZS5jb21tb24uU2ltcGxlUmVzcG9uc2VIAEIJCgdtZXNzYWdlIhMKEVRpY1RhY1RvZU1ldGFkYXRhKokBCg5UaWNUYWNUb2VNb2RlbBIhCh1USUNfVEFDX1RPRV9NT0RFTF9VTlNQRUNJRklFRBAAEhoKFlRJQ19UQUNfVE9FX01PREVMX0VBU1kQARIcChhUSUNfVEFDX1RPRV9NT0RFTF9NRURJVU0QAhIaChZUSUNfVEFDX1RPRV9NT0RFTF9IQVJEEANCyAEKF2NvbS5nYW1lc3NpdGUudGljdGFjdG9lQg5UaWN0YWN0b2VQcm90b1ABWjBnaXRodWIuY29tL0FsZXhXZW5kbGFuZC9nYW1lcy1zaXRlL2JhY2tlbmQvcHJvdG+iAgNHVFiqAhNHYW1lc3NpdGUuVGljdGFjdG9lygITR2FtZXNzaXRlXFRpY3RhY3RvZeICH0dhbWVzc2l0ZVxUaWN0YWN0b2VcR1BCTWV0YWRhdGHqAhRHYW1lc3NpdGU6OlRpY3RhY3RvZWIGcHJvdG8z", [file_common, file_lobby]);

/**
 * TicTacToe game state sent from server to client
 *
 * @generated from message gamessite.tictactoe.TicTacToeGameState
 */
export type TicTacToeGameState = Message<"gamessite.tictactoe.TicTacToeGameState"> & {
  /**
   * 9 elements: move numbers (-1 = empty, 0+ = move number)
   *
   * @generated from field: repeated int32 board = 1;
   */
  board: number[];

  /**
   * Player number who won (0 or 1), null if no winner
   *
   * @generated from field: optional int32 winner = 2;
   */
  winner?: number;

  /**
   * Board positions that form the winning line (empty if no winner)
   *
   * @generated from field: repeated int32 winning_line = 3;
   */
  winningLine: number[];
};

/**
 * Describes the message gamessite.tictactoe.TicTacToeGameState.
 * Use `create(TicTacToeGameStateSchema)` to create a new message.
 */
export const TicTacToeGameStateSchema: GenMessage<TicTacToeGameState> = /*@__PURE__*/
  messageDesc(file_tictactoe, 0);

/**
 * @generated from message gamessite.tictactoe.MakeMoveRequest
 */
export type MakeMoveRequest = Message<"gamessite.tictactoe.MakeMoveRequest"> & {
  /**
   * Board position 0-8
   *
   * @generated from field: int32 position = 1;
   */
  position: number;
};

/**
 * Describes the message gamessite.tictactoe.MakeMoveRequest.
 * Use `create(MakeMoveRequestSchema)` to create a new message.
 */
export const MakeMoveRequestSchema: GenMessage<MakeMoveRequest> = /*@__PURE__*/
  messageDesc(file_tictactoe, 1);

/**
 * Client requests to add an AI player in a particular position
 *
 * @generated from message gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequest
 */
export type TicTacToeAddAIPlayerInPositionRequest = Message<"gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequest"> & {
  /**
   * Player position (0 or 1)
   *
   * @generated from field: int32 position = 1;
   */
  position: number;

  /**
   * AI model type
   *
   * @generated from field: gamessite.tictactoe.TicTacToeModel model = 2;
   */
  model: TicTacToeModel;
};

/**
 * Describes the message gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequest.
 * Use `create(TicTacToeAddAIPlayerInPositionRequestSchema)` to create a new message.
 */
export const TicTacToeAddAIPlayerInPositionRequestSchema: GenMessage<TicTacToeAddAIPlayerInPositionRequest> = /*@__PURE__*/
  messageDesc(file_tictactoe, 2);

/**
 * @generated from message gamessite.tictactoe.ClientTicTacToeWebsocketMessage
 */
export type ClientTicTacToeWebsocketMessage = Message<"gamessite.tictactoe.ClientTicTacToeWebsocketMessage"> & {
  /**
   * @generated from oneof gamessite.tictactoe.ClientTicTacToeWebsocketMessage.message
   */
  message: {
    /**
     * @generated from field: gamessite.tictactoe.MakeMoveRequest make_move = 1;
     */
    value: MakeMoveRequest;
    case: "makeMove";
  } | {
    /**
     * @generated from field: gamessite.lobby.SetPlayerPositionRequest set_player_position = 2;
     */
    value: SetPlayerPositionRequest;
    case: "setPlayerPosition";
  } | {
    /**
     * @generated from field: gamessite.lobby.RemovePlayerPositionRequest remove_player_position = 3;
     */
    value: RemovePlayerPositionRequest;
    case: "removePlayerPosition";
  } | {
    /**
     * @generated from field: gamessite.tictactoe.TicTacToeAddAIPlayerInPositionRequest add_ai_player = 4;
     */
    value: TicTacToeAddAIPlayerInPositionRequest;
    case: "addAiPlayer";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gamessite.tictactoe.ClientTicTacToeWebsocketMessage.
 * Use `create(ClientTicTacToeWebsocketMessageSchema)` to create a new message.
 */
export const ClientTicTacToeWebsocketMessageSchema: GenMessage<ClientTicTacToeWebsocketMessage> = /*@__PURE__*/
  messageDesc(file_tictactoe, 3);

/**
 * @generated from message gamessite.tictactoe.ServerTicTacToeWebsocketMessage
 */
export type ServerTicTacToeWebsocketMessage = Message<"gamessite.tictactoe.ServerTicTacToeWebsocketMessage"> & {
  /**
   * @generated from oneof gamessite.tictactoe.ServerTicTacToeWebsocketMessage.message
   */
  message: {
    /**
     * @generated from field: gamessite.tictactoe.TicTacToeGameState game_state = 1;
     */
    value: TicTacToeGameState;
    case: "gameState";
  } | {
    /**
     * @generated from field: gamessite.lobby.PositionSessionStateResponse session_state = 2;
     */
    value: PositionSessionStateResponse;
    case: "sessionState";
  } | {
    /**
     * @generated from field: gamessite.common.ErrorResponse error = 3;
     */
    value: ErrorResponse;
    case: "error";
  } | {
    /**
     * @generated from field: gamessite.common.SimpleResponse simple_response = 4;
     */
    value: SimpleResponse;
    case: "simpleResponse";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gamessite.tictactoe.ServerTicTacToeWebsocketMessage.
 * Use `create(ServerTicTacToeWebsocketMessageSchema)` to create a new message.
 */
export const ServerTicTacToeWebsocketMessageSchema: GenMessage<ServerTicTacToeWebsocketMessage> = /*@__PURE__*/
  messageDesc(file_tictactoe, 4);

/**
 * @generated from message gamessite.tictactoe.TicTacToeMetadata
 */
export type TicTacToeMetadata = Message<"gamessite.tictactoe.TicTacToeMetadata"> & {
};

/**
 * Describes the message gamessite.tictactoe.TicTacToeMetadata.
 * Use `create(TicTacToeMetadataSchema)` to create a new message.
 */
export const TicTacToeMetadataSchema: GenMessage<TicTacToeMetadata> = /*@__PURE__*/
  messageDesc(file_tictactoe, 5);

/**
 * @generated from enum gamessite.tictactoe.TicTacToeModel
 */
export enum TicTacToeModel {
  /**
   * @generated from enum value: TIC_TAC_TOE_MODEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TIC_TAC_TOE_MODEL_EASY = 1;
   */
  EASY = 1,

  /**
   * @generated from enum value: TIC_TAC_TOE_MODEL_MEDIUM = 2;
   */
  MEDIUM = 2,

  /**
   * @generated from enum value: TIC_TAC_TOE_MODEL_HARD = 3;
   */
  HARD = 3,
}

/**
 * Describes the enum gamessite.tictactoe.TicTacToeModel.
 */
export const TicTacToeModelSchema: GenEnum<TicTacToeModel> = /*@__PURE__*/
  enumDesc(file_tictactoe, 0);

